- id: octoprint
  alias: Notify me when a 3d print finishes
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: 3D print has finished
    service: notify.ios_john_boiless_iphone_x
- action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  alias: Turn off common space lights with a triple tap
  condition: []
  id: '1508091928849'
  trigger:
  - event_data:
      entity_id: zwave.dining_room_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- alias: 'HomeSeer Switch Fix On'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 1
      scene_data: 0
  action:
    - service: switch.turn_on
      data_template:
        entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch" }}'
- alias: 'HomeSeer Switch Fix Off'
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 2
      scene_data: 0
  action:
    - service: switch.turn_off
      data_template:
        entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch" }}'