- id: octoprint
  alias: Notify me when a 3d print finishes
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: 3D print has finished
    service: notify.ios_john_boiless_iphone_x
- action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.christmas_tree_switch
    service: switch.turn_off
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  - data:
      entity_id: switch.master_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off all lights in the house with a triple tap down in the dining room
  condition: []
  id: '1508091928849'
  trigger:
  - event_data:
      entity_id: zwave.dining_room_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: light.kitchen_light_level
    service: light.turn_off
  - data:
      entity_id: light.kitchen_island_light_level
    service: light.turn_off
  - data:
      entity_id: light.dining_room_light_level
    service: light.turn_off
  - data:
      entity_id: light.living_room_light_level
    service: light.turn_off
  - data:
      entity_id: light.kitchen_hallway_light_level
    service: light.turn_off
  - data:
      entity_id: switch.christmas_tree_switch
    service: switch.turn_off
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  alias: Turn off common space lights with a triple tap down in the kitchen
  condition: []
  id: 'common-space-lights-kitchen'
  trigger:
  - event_data:
      entity_id: zwave.kitchen_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- alias: HomeSeer Switch Fix On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 1
      scene_data: 0
  action:
  - service: switch.turn_on
    data_template:
      entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch"}}'
- alias: HomeSeer Switch Fix Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 2
      scene_data: 0
  action:
  - service: switch.turn_off
    data_template:
      entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch"}}'
- action:
  - data:
      entity_id: switch.christmas_tree_switch
    service: switch.turn_on
  alias: Turn on christmas tree lights with double tap up
  id: 'christmas-tree-double-tap-up'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 1
      scene_data: 3
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: switch.christmas_tree_switch
    service: switch.turn_off
  alias: Turn off christmas tree lights with double tap down
  id: 'christmas-tree-double-tap-down'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 2
      scene_data: 3
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_on
  alias: Turn on living room lamp with triple tap up
  id: 'living-room-lamp-triple-tap-up'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 1
      scene_data: 4
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  alias: Turn off living room lamp with triple tap down
  id: 'living-room-lamp-triple-tap-down'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 2
      scene_data: 4
    event_type: zwave.scene_activated
    platform: event