# 3D Print Finished Push notification
- alias: Notify me when a 3d print finishes
  trigger:
    platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
  action:
    service: notify.ios_john_boiless_iphone_x
    data:
      message: 3D print has finished
      data:
        attachment:
          url: http://10.0.0.7/webcam/?action=snapshot
          content-type: jpeg
          hide-thumbnail: false

# Multi-tap Homeseer stuff
# See https://www.home-assistant.io/docs/z-wave/device-specific/#homeseer-switches
- alias: Turn off all lights in the house with a triple tap down in the dining room
  trigger:
    event_data:
      entity_id: zwave.dining_room_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights
    - service: switch.turn_off
      data:
        entity_id: switch.bedroom_lamp_switch
    - service: switch.turn_off
      data:
        entity_id: switch.master_bathroom_fan_switch

- alias: Turn off common space lights with a triple tap down in the kitchen
  trigger:
    platform: event
    event_type: zwave.scene_activated    
    event_data:
      entity_id: zwave.kitchen_light
      scene_data: 4
      scene_id: 2
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_light_level
  - service: light.turn_off
    data:
      entity_id: light.kitchen_island_light_level    
  - service: light.turn_off
    data:
      entity_id: light.dining_room_light_level
  - service: light.turn_off
    data:
      entity_id: light.dining_room_chandelier_level
  - service: light.turn_off
    data:
      entity_id: light.living_room_light_level
  - service: light.turn_off
    data:
      entity_id: light.kitchen_hallway_light_level

- alias: Turn on bedroom lamp with double tap up
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_light
      scene_id: 1
      scene_data: 3
  action:
    service: switch.turn_on
    data:
      entity_id: switch.bedroom_lamp_switch

- alias: Turn off bedroom lamp with double tap down
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_light
      scene_id: 2
      scene_data: 3
  action:
    service: switch.turn_off
    data:
      entity_id: switch.bedroom_lamp_switch

- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
  action:
    service: homekit.start

- alias: Garage Door Open Notification
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        minutes: 30
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garage_door
  condition:
    condition: state
    entity_id: cover.garage_door
    state: 'open'
  action:
    - service: notify.ios_john_boiless_iphone_x
      data:
        message: Garage Door is Open
    - service: timer.start
      entity_id: timer.garage_door

- alias: WD200 Status LED for Garage Door
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
  - platform: state
    entity_id: cover.garage_door
    to: closed
  action:
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 13 # Dimmer LED mode
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Status mode
        {%- else -%}
          Normal mode
        {%- endif -%}
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 21 # Status mode LED 1 (bottom) color
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Red
        {%- else -%}
          White
        {%- endif -%}

- alias: Adjust dim level for WD100 lights when they are turned off afterhours
  trigger:
    - platform: state
      entity_id:
        - light.living_room_light_level
        - light.dining_room_light_level
        - light.dining_room_chandelier_level
        - light.kitchen_island_light_level
        - light.kitchen_light_level
        - light.kitchen_hallway_light_level
        - light.bedroom_light_level
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: time
    after: '21:00:00'
    before: '06:00:00'
  action:
    service: script.set_homeseer_dim_level
    data_template:
      entity_id: "{{ trigger.entity_id }}"
      brightness: >-
        {%- if trigger.entity_id == "light.kitchen_island_light_level" -%}
          50
        {%- else -%}
          3
        {%- endif -%}

- alias: Set dim level for lights at night
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.living_room_light_level
        brightness: 3
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.dining_room_light_level
        brightness: 3
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.dining_room_chandelier_level
        brightness: 3
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_island_light_level
        brightness: 50
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_light_level
        brightness: 3
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_hallway_light_level
        brightness: 3
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.bedroom_light_level
        brightness: 3
    - service: zwave.set_config_parameter
      data_template:
        node_id: 24 # Master Bathroom Light
        parameter: 17
        value: 15

- alias: Set bright level for lights in the morning
  trigger:
    platform: time
    at: "7:00:00"
  action:
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.living_room_light_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.dining_room_light_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.dining_room_chandelier_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_island_light_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_light_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.kitchen_hallway_light_level
        brightness: 255
    - service: script.set_homeseer_dim_level
      data:
        entity_id: light.bedroom_light_level
        brightness: 255
    - service: zwave.set_config_parameter
      data_template:
        node_id: 24 # Master Bathroom Light
        parameter: 17
        value: 99

- alias: Push notify when power goes out
  trigger:
    platform: numeric_state
    entity_id: sensor.nut_ups_input_voltage
    below: 60
  action:
    service: notify.ios_john_boiless_iphone_x
    data:
      message: Power is out

- alias: Push notify when smoke alarm is triggered
  trigger:
    - platform: state
      entity_id: sensor.hallway_smoke_alarm_state
      from: "Unknown"
    - platform: state
      entity_id: sensor.hallway_smoke_alarm_state
      from: "Idle"
  action:
    service: notify.ios_john_boiless_iphone_x
    data_template:
      message: Smoke alarm is triggered for {{ trigger.to_state.state }}

- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
    service: notify.notify
    data_template:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."

- alias: Soundbar to Aux when the Everywhere group is playing
  trigger:
    - platform: state
      entity_id: media_player.everywhere
      to: 'playing'
    - platform: state
      entity_id: media_player.everywhere
      from: 'playing'
  action:
    service: mqtt.publish
    data_template:
      topic: 'irblaster/tx'
      payload_template: >-
        {"type":"NEC","code":"
        {%- if trigger.to_state.state == 'playing' -%}
          FF8D72
        {%- else -%}
          FF13EC
        {%- endif -%}"}
