# 3D Print Finished Push notification
- id: octoprint
  alias: Notify me when a 3d print finishes
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: notify.ios_john_boiless_iphone_x
    data:
      message: 3D print has finished
      data:
        attachment:
          url: https://house.johnboiles.com:15000/webcam/?action=snapshot
          content-type: jpeg
          hide-thumbnail: false
        push:
          category: "print-finished" # Needs to match the top level identifier you used in the ios configuration
- alias: Printer off via push action
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: PRINTER_OFF
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.3d_printer
# Multi-tap Homeseer stuff
- action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  - data:
      entity_id: switch.master_bathroom_fan_switch
    service: switch.turn_off
  alias: Turn off all lights in the house with a triple tap down in the dining room
  condition: []
  id: '1508091928849'
  trigger:
  - event_data:
      entity_id: zwave.dining_room_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: light.kitchen_light_level
    service: light.turn_off
  - data:
      entity_id: light.kitchen_island_light_level
    service: light.turn_off
  - data:
      entity_id: light.dining_room_light_level
    service: light.turn_off
  - data:
      entity_id: light.living_room_light_level
    service: light.turn_off
  - data:
      entity_id: light.kitchen_hallway_light_level
    service: light.turn_off
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  alias: Turn off common space lights with a triple tap down in the kitchen
  condition: []
  id: 'common-space-lights-kitchen'
  trigger:
  - event_data:
      entity_id: zwave.kitchen_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
- alias: HomeSeer Switch Fix On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 1
      scene_data: 0
  action:
  - service: switch.turn_on
    data_template:
      entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch"}}'
- alias: HomeSeer Switch Fix Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 2
      scene_data: 0
  action:
  - service: switch.turn_off
    data_template:
      entity_id: '{{"switch." + trigger.event.data.entity_id.split(".")[1] + "_switch"}}'
- action:
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_on
  alias: Turn on living room lamp with triple tap up
  id: 'living-room-lamp-triple-tap-up'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 1
      scene_data: 4
    event_type: zwave.scene_activated
    platform: event
- action:
  - data:
      entity_id: switch.living_room_lamp_switch
    service: switch.turn_off
  alias: Turn off living room lamp with triple tap down
  id: 'living-room-lamp-triple-tap-down'
  condition: []
  trigger:
  - event_data:
      entity_id: zwave.living_room_light
      scene_id: 2
      scene_data: 4
    event_type: zwave.scene_activated
    platform: event
- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
  action:
    - service: homekit.start

- alias: Garage Door Open Notification
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        minutes: 30
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garage_door
  condition:
    condition: state
    entity_id: cover.garage_door
    state: 'open'
  action:
    - service: notify.ios_john_boiless_iphone_x
      data:
        message: Garage Door is Open
    - service: timer.start
      entity_id: timer.garage_door

- alias: WD200 Status LED for Garage Door
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
  - platform: state
    entity_id: cover.garage_door
    to: closed
  action:
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 13 # Dimmer LED mode
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Status mode
        {%- else -%}
          Normal mode
        {%- endif -%}
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 21 # Status mode LED 1 (bottom) color
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Red
        {%- else -%}
          White
        {%- endif -%}

- alias: Keep the bathroom light dim at night
  trigger:
  - platform: time
    at: "23:30:00"
  action:
  - service: zwave.set_config_parameter
    data_template:
      node_id: 24
      parameter: 17
      value: 15

- alias: Keep the bathroom light bright by default during the day
  trigger:
  - platform: time
    at: "07:30:00"
  action:
  - service: zwave.set_config_parameter
    data_template:
      node_id: 24
      parameter: 17
      value: 99

- alias: Push notify when power goes out
  trigger:
    - platform: numeric_state
      entity_id: sensor.nut_ups_input_voltage
      below: 60
  action:
    - service: notify.ios_john_boiless_iphone_x
      data:
        message: Power is out

- alias: Push notify when smoke alarm is triggered
  trigger:
    - platform: state
      entity_id: sensor.hallway_smoke_alarm_state
      from: "Unknown"
    - platform: state
      entity_id: sensor.hallway_smoke_alarm_state
      from: "Idle"
  action:
    - service: notify.ios_john_boiless_iphone_x
      data_template:
        message: Smoke alarm is triggered for {{ trigger.to_state.state }}

- alias: Soundbar to Aux when the Everywhere group is playing
  trigger:
  - platform: state
    entity_id: media_player.everywhere
    to: 'playing'
  - platform: state
    entity_id: media_player.everywhere
    from: 'playing'
  action:
  - service: mqtt.publish
    data_template:
      topic: 'irblaster/tx'
      payload_template: >-
        {"type":"NEC","code":"
        {%- if trigger.to_state.state == 'playing' -%}
          FF8D72
        {%- else -%}
          FF13EC
        {%- endif -%}"}
