homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

system_health:

recorder:
  db_url: !secret mysql_db_url
  purge_keep_days: 120

ecobee:
  api_key: !secret ecobee_api_key

octoprint:
  host: 10.0.0.7
  api_key: !secret octoprint_api_key
  bed: true

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

panel_iframe:
  jupyterlab:
    title: JupyterLab
    icon: mdi:flask
    url: http://10.0.0.2:7777

logi_circle:
  client_id: !secret logi_circle_client_id
  client_secret: !secret logi_circle_client_secret
  api_key: !secret logi_circle_api_key
  redirect_uri: !secret logi_circle_redirect_uri

camera:
  - platform: mjpeg
    name: OctoPrint Camera
    mjpeg_url: http://10.0.0.7/webcam/?action=stream
    still_image_url: http://10.0.0.7/webcam/?action=snapshot

script: !include scripts.yaml

python_script:

# Enables the frontend
frontend:

# Enables configuration UI
config:

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - group
      - automation
      - script
      - device_tracker
      - climate
      - binary_sensor
    exclude_entities:
      - switch.twitter_laptop_wol
      - light.master_bathroom_light_level_2
      - switch.3d_printer
      - switch.twitter_laptop_wol
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_temperature
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_actual_bed_temp
      - sensor.outside_heatindex
      - sensor.outside_dewpoint
      - sensor.inside_heatindex
      - sensor.inside_dewpoint
      - sensor.basement_heatindex
      - sensor.basement_dewpoint
      - switch.home_assistant_pi4
      - sensor.bedroom_temperature
      - sensor.dht22_absolutehumidity
      - sensor.dht22_dewpoint
      - sensor.dht22_heatindex
      - sensor.living_room_temperature
      - sensor.mh_z19_temperature

cloud:
  alexa:
    filter:
      exclude_domains:
        - group
        - automation
        - script
        - sensor
        - device_tracker
      exclude_entities:
        - switch.twitter_laptop_wol
        - light.master_bathroom_light_level_2
        - switch.3d_printer
        - sensor.octoprint_target_bed_temp
        - sensor.octoprint_actual_bed_temp
        - sensor.outside_heatindex
        - sensor.outside_dewpoint
        - sensor.inside_heatindex
        - sensor.inside_dewpoint
        - sensor.basement_heatindex
        - sensor.basement_dewpoint
        - switch.home_assistant_pi4
        - sensor.bedroom_temperature
        - sensor.dht22_absolutehumidity
        - sensor.dht22_dewpoint
        - sensor.dht22_heatindex
        - sensor.living_room_temperature
        - sensor.mh_z19_temperature

ios:

default_config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

cover:
  - platform: mqtt
    name: Garage Door
    state_topic: "garage/door"
    command_topic: "garage/button"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "OPENED"
    state_closed: "CLOSED"
    optimistic: false
    retain: false
    value_template: '{{ value }}'

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - temperature
      - precip_probability
      - nearest_storm_distance
      - wind_speed
      - wind_bearing

  - platform: command_line
    name: CPU Temp
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "ºC"
    value_template: '{{ value | multiply(0.001) | round(2) }}'

  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Outside Temperature'
    unit_of_measurement: '°F'
    expire_after: 600
    value_template: '{{ value_json.temperature_F if value_json.channel == 2 else states.sensor.outside_temperature.state }}'

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Outside Humidity'
    unit_of_measurement: '%'
    expire_after: 600
    value_template: '{{ value_json.humidity if value_json.channel == 2 else states.sensor.outside_humidity.state}}'

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Basement Temperature'
    unit_of_measurement: '°F'
    expire_after: 600
    value_template: '{{ value_json.temperature_F if value_json.channel == 5 else states.sensor.basement_temperature.state}}'

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Basement Humidity'
    unit_of_measurement: '%'
    expire_after: 600
    value_template: '{{ value_json.humidity if value_json.channel == 5 else states.sensor.basement_humidity.state}}'

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Izzy Room Temperature'
    unit_of_measurement: '°F'
    expire_after: 600
    value_template: '{{ value_json.temperature_F if value_json.channel == 7 else states.sensor.izzy_room_temperature.state}}'

  - platform: mqtt
    state_topic: 'rtl_433/raw'
    name: 'Izzy Room Humidity'
    unit_of_measurement: '%'
    expire_after: 600
    value_template: '{{ value_json.humidity if value_json.channel == 7 else states.sensor.izzy_room_humidity.state}}'

  # - platform: miflora
  #   mac: 'C4:7C:8D:62:73:AC'
  #   name: Peace Lily
  #   monitored_conditions:
  #     - moisture
  #     - temperature
  #     - light
  #     - conductivity
  #     - battery

  # - platform: miflora
  #   mac: 'C4:7C:8D:62:6C:D2'
  #   name: Dracaena
  #   monitored_conditions:
  #     - moisture
  #     - temperature
  #     - light
  #     - conductivity
  #     - battery

  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Job Percentage

  - platform: thermal_comfort
    sensors:
      basement:
        friendly_name: Basement
        temperature_sensor: sensor.basement_temperature
        humidity_sensor: sensor.basement_humidity
      inside:
        friendly_name: Inside
        temperature_sensor: sensor.thermostat_temperature
        humidity_sensor: sensor.thermostat_humidity
      outside:
        friendly_name: Outside
        temperature_sensor: sensor.outside_temperature
        humidity_sensor: sensor.outside_humidity
      dht22:
        friendly_name: DHT22
        temperature_sensor: sensor.dht22_temperature
        humidity_sensor: sensor.dht22_humidity

  - platform: template
    sensors:
      # From https://community.home-assistant.io/t/first-alert-z-wave-smoke-carbon-monoxide-detectors-dont-show-up-in-home-assistant/1332/15
      hallway_smoke_alarm_state:
        value_template: >-
          {%- if is_state("sensor.hallway_smoke_alarm_alarm_level", "0") -%}
            Idle
          {%- elif is_state("sensor.hallway_smoke_alarm_alarm_type", "1") -%}
            Fire
          {%- elif is_state("sensor.hallway_smoke_alarm_alarm_type", "2") -%}
            CO
          {%- elif is_state("sensor.hallway_smoke_alarm_alarm_type", "12") -%}
            Testing
          {%- elif is_state("sensor.hallway_smoke_alarm_alarm_type", "13") -%}
            Idle
          {% else -%}
            Unknown
          {%- endif -%}
        friendly_name: 'Hallway Smoke Alarm'

  - platform: nut
    host: 10.0.0.6
    alias: ups
    resources:
      - ups.load
      - ups.realpower.nominal
      - input.voltage
      - battery.runtime
      - battery.charge
      - battery.voltage

tplink:
  discovery: false
  switch:
    - host: 10.0.0.5

switch:
  - platform: wake_on_lan
    name: "Twitter Laptop WOL"
    # mac: "F4-5C-89-A3-A7-73" # Twitter Laptop Wifi
    mac: "0C-4D-E9-AA-C6-52" # Thunderbolt ethernet (with 'tw' on it)
    host: tw-mbp-jboiles.local
  - platform: template
    switches:
      hvac_fan:
        friendly_name: "Fan"
        value_template: "{{ is_state_attr('climate.thermostat', 'fan_mode', 'on') }}"
        turn_on:
          service: climate.set_fan_mode
          data:
            entity_id: climate.thermostat
            fan_mode: "on"
        turn_off:
          service: climate.set_fan_mode
          data:
            entity_id: climate.thermostat
            fan_mode: "auto"

fan:
  - platform: mqtt
    name: "Basement Fan"
    command_topic: "fan/power"
    speed_command_topic: "fan/power"
    payload_on: "100"
    payload_off: "0"
    payload_low_speed: "90"
    payload_medium_speed: "95"
    payload_high_speed: "100"
    speeds:
      - low
      - medium
      - high

group: !include groups.yaml

automation: !include automations.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config:
    light.master_bathroom_light_level:
      refresh_value: true
      delay: 3
      polling_intensity: 2
    light.bedroom_light_level:
      refresh_value: true
      delay: 2
    light.living_room_light_level:
      refresh_value: true
      delay: 2
    light.dining_room_light_level:
      refresh_value: true
      delay: 2
    light.kitchen_light_level:
      refresh_value: true
      delay: 2
    light.kitchen_island_light_level:
      refresh_value: true
      delay: 2
    light.dining_room_chandelier_level:
      refresh_value: true
      delay: 2
    light.kitchen_hallway_light_level:
      refresh_value: true
      delay: 2

unifi:
  controllers:
  - host: 10.0.0.6
    site: Boiles Home
    block_client:
    - 'ac:cf:5c:33:88:45' # Christina's iPad Air
    - '28:6a:ba:8e:95:18' # John's iPad2

mqtt:
  client_id: home-assistant
  discovery: true
  discovery_prefix: homeassistant
  password: !secret mqtt_password

# Used for the automation that notifies every 30 min when the garage is open.
timer:
  garage_door:
    duration: '00:30:00'

route53:
  aws_access_key_id: !secret route53_access_key_id
  aws_secret_access_key: !secret route53_secret_access_key
  zone: !secret route53_zone
  domain: !secret route53_domain
  records:
    - house

media_player:
  - platform: universal
    name: Soundbar
    children:
      - media_player.living_room
      - media_player.everywhere
    commands:
      turn_on:
        service: mqtt.publish
        data:
          topic: 'irblaster/tx'
          # The following command is the correct command for on/off, but HomeKit
          # has a quirk where it tries to make sure the soundbar is on before sending
          # volume commands. But since the on/off IR codes are the same this ends
          # up turning the sound bar off. I'm working around this by just sending the
          # volume up command since it also will turn on the sound bar.
          # payload: '{"type":"NEC","code":"FF02FD"}'
          payload: '{"type":"NEC","code":"FF827D"}'
      turn_off:
        service: mqtt.publish
        data:
          topic: 'irblaster/tx'
          payload: '{"type":"NEC","code":"FF02FD"}'
      volume_up:
        service: mqtt.publish
        data:
          topic: 'irblaster/tx'
          payload: '{"type":"NEC","code":"FF827D"}'
      volume_down:
        service: mqtt.publish
        data:
          topic: 'irblaster/tx'
          payload: '{"type":"NEC","code":"FFA25D"}'
      volume_mute:
        service: mqtt.publish
        data:
          topic: 'irblaster/tx'
          payload: '{"type":"NEC","code":"FF12ED"}'
      select_source:
        service: mqtt.publish
        data_template:
          topic: 'irblaster/tx'
          payload: >-
            {"type":"NEC","code":"
            {%- if source == 'Optical' -%}
              FF13EC
            {%- elif source == 'Aux 1' -%}
              FF8D72
            {%- elif source == 'USB' -%}
              FF857A
            {%- elif source == 'Bluetooth' -%}
              FF44BB
            {%- elif source == 'Aux 2' -%}
              FF4DB2
            {%- elif source == 'Digital' -%}
              FF936C
            {%- endif -%}"}
